name: Deploy AWS Lambdra

on:
  push: 
    branches: 
      - main
    paths:
      - 'lambda/'

jobs:
  deploy-lambda: # name of our job
    runs-on: ubuntu-latest #Sets or specifies the runner
    steps:
    - uses: actions/checkout@v2
    
    - name: Set Up Python #Sets up python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies #Installs Packages
      run: |
        python -m pop install upgrade pop
        pop install -r lambda/requirements.txt -t lambda/

    - name: Configure AWS Creds #Sets up AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-access-secret-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Lambda Function # Zips Lambda Directory and Updates Lambda Function
      run: |
        cd lambda
        zip -r lambda.zip .
        aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file file://lambda.zip