name: Deploy AWS Lambda

on:
  push: 
    branches: 
      - main
    paths:
      - 'lambda/**'

jobs:
  deploy-lambda: # name of our job
    runs-on: ubuntu-latest #Sets or specifies the runner
    steps:
    - uses: actions/checkout@v4

    - name: Set Up Python #Sets up python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies #Installs Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt -t lambda/

    - name: Configure AWS Creds #Sets up AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Lambda Function # Zips Lambda Directory and Updates Lambda Function
      run: |
        zip -r lambda.zip lambda/
        aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip


